name: Managed Build and Push Chart to Repository
description: Builds and pushes a chart to a managed repository
inputs:
  chart-path:
    description: Path to the chart to build and push
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and push chart to ECR
      uses: atomicfi/action-build-push-chart-ecr@v1.1.0-beta.1
      with:
        chart-path: ${{ inputs.chart-path }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
        role-duration-seconds: 900
        role-to-assume: arn:aws:iam::892765726487:role/GithubActionsRole
