name: Managed Build and Push Chart to Repository
description: Builds and pushes a chart to a managed repository
uses:
  chart-path:
    description: Path to the chart to build and push
    required: true
run:
  using: "composite"
  steps:
    - name: Build and push chart to ECR
      uses: atomicfi/action-build-push-chart-ecr@v1
      with:
        chart-path: ${{ inputs.chart-path }}
        aws-access-key-id: ${{ secrets.GH_USER_ACCESS_TOKEN }}
        aws-secret-access-key: ${{ secrets.GH_USER_SECRET }}
        aws-region: us-east-1
        role-duration-seconds: 900
        role-to-assume: arn:aws:iam::892765726487:role/GithubActionsRole
